### ISSUE TITLE
Threads and events achievements

### ISSUE THREAD

**Issue by jonasswiatek** [jonasswiatek/strokes#15]
Create achievements for Threading and Events

**Comment by timdams** [comment]
Hey, I'm looking into some event achievement and use this small snippet as test code:
  1      public delegate void ChangedEventHandler(object sender, EventArgs e);
  2     public event ChangedEventHandler Changed;

  3        public TestFile()
        {
  4          this.Changed += new ChangedEventHandler(TestFile_Changed);

  5          Changed(this, EventArgs.Empty);
        }

  6      void TestFile_Changed(object sender, EventArgs e)
        {
  7          throw new NotImplementedException();
        }

However,
I was thinking that the VisitRaiseEvent and VisitAddEventRegion would be visited on lines 5 and 4 respectively. Unfortuntaly it doesn't (5 is an InvocationAssignment and 4 is an AssignmentExpression). 

Anyone know the correct C# syntax to visit these 2 region (and VisitRemoveEventRegion) because I thought my snippet was the way to go...

**Comment by jonasswiatek** [comment]
Hmm, yea that's a good question. I'll have a look at it after dinner.

**Comment by timdams** [comment]
Got some event/thread achievements done as proof-of-concept.So let's close this one and see the issue-list shrink :D
