### ISSUE TITLE
Achievement unlocking while typing code

### ISSUE THREAD

**Issue by jonasswiatek** [jonasswiatek/strokes#25]
Originally when I made the first POC on this project 6 months ago, I had a halfassed system that unlocked achievements while the code was being typed (it's significantly more complicated than to just dispatch against ensured functioning code).

However, the idea is still in my head, and I want to hear you opinion on it. Would it be awesome or just annoying?

**Comment by clausjoergensen** [comment]
Considering it'll be for Strokes only projects, I'd say it's okay'ish. Depends how bad it performs. 

But I'd rather get some more detailed compilation information, for advanced achievements.

**Comment by jonasswiatek** [comment]
Like how much of a challenge was done right?

**Comment by timdams** [comment]
I think it would distract students while coding since they might unlock stuff while in the middle of trying to grasp some new concept. Or they might by accident unlock stuff and by the time they react they allready deleted part of the code that unlocked it. So in a whole, not a big fan. I think our energy should be spend indeed on trying to get more advanced compilation information. (I'm also still a big fan on more 'count-based stuff' like 'created 10 different classes'; 'placed 1000 breakpoints'). Just my two cents.

**Comment by clausjoergensen** [comment]
For compilation information, it's more about getting real type information , such as if a type is a interface, etc. Tim been requesting that a lot in his comments.

**Comment by jonasswiatek** [comment]
Ah, so more helpers in the NRefactoryAchievement class?

**Comment by clausjoergensen** [comment]
Not sure, I'll have to dive more into how NRefactory works, and what information we can get from it. A task for the weekend I guess :p

**Comment by jonasswiatek** [comment]
It can see everything - the trick is to do a sort of "multipass" parsing of the files. I'll make an example of it (it makes a lot of sense when you see it)

**Comment by vlad2135** [comment]
I second Tim, I'm not sure that popping of achievements in the middle of typing is a good idea. And then it will break some already implemented achievements like EmptyMethodAchievement.

**Comment by jonasswiatek** [comment]
Yea, it wouldn't work very well. Code isn't a game where there is a transitioning state that can be measured. Code is only in a state of anything when it's compiled. I'll spend my time on more usefull features :D
