### ISSUE TITLE
Make Strokes only active when using the Strokes Project Template

### ISSUE THREAD

**Issue by jonasswiatek** [jonasswiatek/strokes#3]
I'd like your opinion on a change to the strokes mechanics:

I'm considering locking the achievement scanner so it only runs when something is compiled from a Strokes Achievement Project (instead of any C# project), the reason for this is:

1) It'll make people actually have the extension enabled and not disable it because it'll interfere with normal code work.
2) We can provide a set of other utilities that enabled when that type of project is loaded
3) We can default on verifying code online, since we can safely assume that people are not going to write "omfg production secret"-code inside an Achievement Template - instead of creating a huge "please approve this code before we send it off to the website for verification".

Especially because I'd really like a feature online, that'll showcase how other people solved an achievement (I'm thinking that you unlock the possibility to see other peoples solution to a specific achievement/challenge, the moment you unlock that same achievement). People will be less scared when it's code they've written specifically to solve achievements.

**Comment by timdams** [comment]
I certainly agree (on all points.. I didn’t even consider the fact that one might accidently upload ubersecret code…hihi, would be a very neat trick of side-channel attacking :p (yeah, prepping a course on security  so it’s all wifihacking, metasploit , etc these days) .

Couldn’t this be ‘simply’ integrated in the existing Challenge template? I.e. a parent template that enables the achievements,the challenge template then inherits from this template and adds the necessary refs to the student.dll?

-----Oorspronkelijk bericht-----
Van: Jonas Swiatek [mailto:reply@reply.github.com]
Verzonden: zaterdag 1 oktober 2011 19:11
Aan: Tim Dams
Onderwerp: [strokes] Make Strokes only active when using the Strokes Project Template (#3)

I'd like your opinion on a change to the strokes mechanics:

I'm considering locking the achievement scanner so it only runs when something is compiled from a Strokes Achievement Project (instead of any C# project), the reason for this is:

1) It'll make people actually have the extension enabled and not disable it because it'll interfere with normal code work.

2) We can provide a set of other utilities that enabled when that type of project is loaded

3) We can default on verifying code online, since we can safely assume that people are not going to write "omfg production secret"-code inside an Achievement Template - instead of creating a huge "please approve this code before we send it off to the website for verification".

Especially because I'd really like a feature online, that'll showcase how other people solved an achievement (I'm thinking that you unlock the possibility to see other peoples solution to a specific achievement/challenge, the moment you unlock that same achievement). People will be less scared when it's code they've written specifically to solve achievements.

## 

Reply to this email directly or view it on GitHub:

https://github.com/jonasswiatek/strokes/issues/3

**Comment by jonasswiatek** [comment]
I don't think project templates support inheritance in any way - but it's pretty trivial to make them, so I'll just make one.

Question is: should we have an achievement project template and then a challenge project template - or just make them one-and-the-same?

**Comment by clausjoergensen** [comment]
Only 1 template please. More than one would be more confusing than good is.

**Comment by alexrp** [comment]
Why not let people enable Strokes on a per-project or solution basis? You could store the configuration in some *.user file (as those are generally kept out of source control).

**Comment by jonasswiatek** [comment]
I'll keep it to one template. Some settings to enable strokes outside this template could also be a nice thing
