### ISSUE TITLE
Challenge Wizard in Project Template

### ISSUE THREAD

**Issue by jonasswiatek** [jonasswiatek/strokes#30]
I've removed the library include of Strokes.Challenges from the VsTemplate. The reason for this is that the dll included there consistently become out-of-synch with the correct one.

I want to replace this with a Wizard that simply goes:

1) Bla bla welcome to challenges
2) Choose your challenge [drop down or something]
3) OK [dll becomes included from the %AppData%-directory and throws in a barebone implementation

I'll work on this

**Comment by timdams** [comment]
I think that would be an awesome addition since this would indeed make the challenges more userfriendly for newbie students.

-----Oorspronkelijk bericht-----
Van: Jonas Swiatek [mailto:reply@reply.github.com] 
Verzonden: donderdag 13 oktober 2011 19:33
Aan: Tim Dams
Onderwerp: [strokes] Challenge Wizard in Project Template (#30)

I've removed the library include of Strokes.Challenges from the VsTemplate. The reason for this is that the dll included there consistently become out-of-synch with the correct one.

I want to replace this with a Wizard that simply goes:

1) Bla bla welcome to challenges
2) Choose your challenge [drop down or something]
3) OK [dll becomes included from the %AppData%-directory and throws in a barebone implementation

I'll work on this

## 

Reply to this email directly or view it on GitHub:
https://github.com/jonasswiatek/strokes/issues/30

**Comment by jonasswiatek** [comment]
I've just pushed a version of this - check it out.

IMPORTANT: Do a Project CLEAN and then FULL REBUILD (just the first time after pull), to ensure that the ProjectTemplate.zip-files inside the VSIX updated properly).

It's still all just thrown into the C# Category. Try to right click (when you've got a NEW StrokesAchievement project) -> Add Item -> Find the Caesar Challenge and Calculator Challenge. Watch magic happen!

**Comment by timdams** [comment]
Ok, cool feature and works like a charm!
Will update the 'getting started doc (in /docs/) to reflect these changes.

**Comment by jonasswiatek** [comment]
This of course should all be a sub category of Visual C#, but getting it in there has proven to be unreasonably complicated.

**Comment by jonasswiatek** [comment]
Sweet merciful jesus this finally worked out. The MSDN Documentation on this, is AT BEST complete fucking shit. But by chance I found a comment on one of the documentation pages that pointed out that instead of implementing a shitload of COM, one could just do this with some cleaver use of MSBuild directives.

**Comment by timdams** [comment]
Hooray!
