### ISSUE TITLE
Funny achievements: an idea

### ISSUE THREAD

**Issue by jonasswiatek** [jonasswiatek/strokes#36]
I was thinking that maybe we should change the funny achievements concept a little:

1) Make the hidden untill unlocked
2) Rename the category to "Certificates of Excellence" or something else (to denote that it's the kinda shit that people inadventendly do when they code).

Meaning that you'll get an achievement you don't expect, because you did something silly, stupid, funny or similar activity in your code. A bit like the "Feats of Strength" achievements in World of Warcraft. You don't know they exist before you unlock them.

**Comment by clausjoergensen** [comment]
Yeah, I like that idea.

**Comment by timdams** [comment]
I really like thay way of reasoning! Only the journeyman name aint that top ;)

Tim Dams

---

Sent from my Windows Phone ( sorry for possible typos or short answer)

---

From: Jonas Swiatek
Sent: 19/10/2011 15:24
To: Tim Dams
Subject: [strokes] Funny achievements: an idea (#36)

I was thinking that maybe we should change the funny achievements concept a little:

1) Make the hidden untill unlocked
2) Rename the category to "Journeyman" or something else (to denote that it's the kinda shit that people inadventendly do when they code).

Meaning that you'll get an achievement you don't expect, because you did something silly, stupid, funny or similar activity in your code. A bit like the "Feats of Strength" achievements in World of Warcraft. You don't know they exist before you unlock them.

## 

Reply to this email directly or view it on GitHub:
https://github.com/jonasswiatek/strokes/issues/36

**Comment by jonasswiatek** [comment]
Yea, I also edited the issue text a few times to select another name for them :P

**Comment by jonasswiatek** [comment]
I think I'll split the achievement dispatch and so forth into two seperate branches of achievements:
The static analysis type and achievements that subscribe to very specific visual studio events.

I'm thinking two achievement projects:
1) Learning type achievements (pretty much what we've got now)
2) Lol/feats/entertainment achievements: stuff like what we've got in funny now, and stuff like "when this obscure compiler error occurs" and others.

I'm thinking that most achievements in (2) are hidden until unlocked. This type of achievement requires some work to be done in the dispatch system, because the direction of the flow is different. The achievements need to offer them selves as completed from their own thread context, rather than from the dispatching thread(s) that gets launched during compile now.

When I've done my home work for my Software Architecture class this week, I'll branch out and see what I can make

**Comment by jonasswiatek** [comment]
Also: I'm thinking that the 2nd project's achievements are enabled in all projects default.

**Comment by jonasswiatek** [comment]
This is "implemented" - at least the base bone structure is. Now it's a matter of us dancing the dance of doom with the Visual Studio Extension framework. May god have mercy on our souls (you'll see, when you dive into the documentation)

**Comment by timdams** [comment]
Banzaaaai!

Tim Dams

---

Sent from my Windows Phone ( sorry for possible typos or short answer)
